### ISSUE TITLE
CSS 实现居中的常用方法

### ISSUE THREAD

**Issue by jesusLove** [jesusLove/Owenli_Blog#1]
# 目录

* flexbox 实现元素居中
* CSS transform 元素居中
* 使用 margin: 0 auto; 实现水平居中
* text-align 文本居中
* 使用 position: absolute 绝度定位实现居中
* 使用 calc() 函数实现居中
* line-height 单行文本居中
* 三行代码实现任意元素垂直居中

# 1、使用 flexbox 实现水平垂直居中

HTML: 

```html
<div class="container">
  <div class="element"></div>
</div>
```

CSS:

```css
.container {
  height: 300px;
  display: flex;
  justify-content: center; // 水平居中
}
.element {
  align-self: center; // 垂直居中
}
```

或者

```css
.container {
  height: 300px;
  display: flex;
  justify-content: center; // 水平居中
  align-items: center; // 垂直居中
}
```

## 兼容问题

Flexbox 是 CSS3 中被引入，意味着它是相对较新的技术没有被所有的浏览器支持。

支持情况如下：

* IE8 和 9 不支持 flexbox。如果想用 flex 属性，需要使用 [flexbox polyfill]() 实现，不过嘛，效果差了点不在维护了。
* IE10 支持 flexbox 的早起版本，需要使用供应商前缀。不支持 flex-grow，flex-shrink 和 flex-basis等属性。
* IE11 支持当前的 flexbox 标准，不过有 bug。
* Chrome、Firefox 和 Edge 支持。
* Safari 9+ 支持 flexbox 不需要前缀。低版本需要加 `-webkit` 前缀。

关于 flexbox 支持问题可以参考这个问题 
> 参考 [Flexbox浏览器支持 - stackoverflow](https://stackoverflow.com/questions/35137085/flexbox-code-working-on-all-browsers-except-safari-why/35137869#35137869) 。

<html>
<a style="color: #F78AE0; font-size: 20px;" href="https://codepen.io/Owen_li/pen/dyPNNeg">在线演示-CodePen</a>
</html>

# 2、CSS transform

transform 是基于元素大小的属性，不需要知道元素的宽高。

```css
.container {
  position: relative;
}
.element {
  position: absolute; // 绝对定位
  top: 50%; 
  left: 50%;
  transform: translate(-50%, -50%);
}
```

## 兼容问题

`translate` 属性需要添加前缀支持旧浏览器。IE8及更低版本不支持。

```css
-webkit-transform: translate(-50%, -50%); /* Chrome, Safari, Opera, Android */ 
    -ms-transform: translate(-50%, -50%); /* IE 9 */
        transform: translate(-50%, -50%);
```

<html>
<a style="color: #F78AE0; font-size: 20px;" href="https://codepen.io/Owen_li/pen/YzPNZmG">在线演示-CodePen</a>
</html>

# 3、使用 margin: 0 auto; 实现水平居中

```html
<div class="container">
  <div class="element"></div>
  <img class="element-image"
src="https://www.baidu.com/img/superlogo_c4d7df0a003d3db9b65e9ef0fe6da1ec.png?where=super" />
</div>
```

CSS

```css
/* 
  margin: 0 auto; 居中布局
*/
.element {
  margin: 0 auto; 
}
.element-image {
  display: block;
  width: 200px;
  border: 1px solid red;
  margin: 0 auto;
}
```

# 4、text-align 文本居中

最简单的元素文本居中使用 `text-align:center` 属性。

```html
<p>Lorem ipsum</p>
```
CSS :

```css
p {
    text-align:  center;
}
```

# 5、使用 position: absolute 绝度定位实现居中

```html
<div class="container">
  <img src="https://www.baidu.com/img/superlogo_c4d7df0a003d3db9b65e9ef0fe6da1ec.png?where=super" alt="">
</div>
```
CSS: 

```css
// 布局 
.container {
  position: relative;
  height: 500px;
}
// 需要有初始的宽高
img {
  position: absolute;
  margin: auto;
  top: 0;
  right: 0;
  left: 0;
  bottom: 0;
}
```
<html>
<a style="color: #F78AE0; font-size: 20px;" href="https://codepen.io/Owen_li/pen/RwNpZwO?editors=1100">在线演示-CodePen</a>
</html>

# 6、使用 calc() 函数实现居中

```html
<div class="container">
  <div class="center"></div>
</div>
```

CSS：

```css
.container {
  height: 300px;
  background-color: #5CC9F5;
  position: relative;
}

.center {
  position: absolute;
  height: 100px;
  width: 100px;
  background-color: #F78AE0;
  top: calc(50% - 100px / 2); // height 的二分之一
  left: calc(50% - 100px / 2); // width 二分之一
}
```
PS: `calc()` 是 `CSS3` 新语法的一部分，可以计算元素的大小和位置，只可以是像素、百分比等。注意使用时需要注意空格问题，两个值之间必须要空格。

<html>
<a style="color: #F78AE0; font-size: 20px;" href="https://codepen.io/Owen_li/pen/VwYpzaR?editors=1100">在线演示-CodePen</a>
</html>

# 7、line-height 单行文本居中

`line-height` 实现元素中 **单行文本** 的垂直居中。

```html
<div class="container">
   line-height 实现文本垂直居中
</div>
```
CSS
```css
.container {
  height: 100px;
  background-color: #5CC9F5;
  line-height: 100px;
}
```
PS: 文本换行时，结果并没有居中。

<html>
<a style="color: #F78AE0; font-size: 20px;" href="https://codepen.io/Owen_li/pen/yLyMoMo?editors=1100">在线演示-CodePen</a>
</html>

# 8、三行代码实现任意元素垂直居中

```html
<div class="parent">
  <div class="vertical">Vertical aligned text!</div>
</div>
```
CSS 

```css
// 父容器设置高度
.parent {
  height: 200px;
  background-color: #5CC9F5;
}
.vertical {
  position: relative;
  top: 50%;
  transform: translateY(-50%);
}
```
PS: 使用三行代码实现垂直居中，只要设置父容器高度。

<html>
<a style="color: #F78AE0; font-size: 20px;" href="https://codepen.io/Owen_li/pen/dyPvzQb?editors=1100">在线演示-CodePen</a>
</html>
